language: node_js
sudo: true
service: docker

node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

cache:
  directories:
    - "node_modules"

env:
  global:
  - ZOOKEEPER_PEERS=localhost:2181
  - KAFKA_PEERS=localhost:9092

before_install:
  - ./run_docker.sh

